name: Android Qt 6

on:
  push:
    paths-ignore:
    - scripts/docker/**
  pull_request:
    paths-ignore:
    - scripts/docker/**
    branches:
    - master
  workflow_dispatch:

env:
  RELEASE_PUBLISHER: "true"

permissions: read-all

jobs:
  build:
    outputs:
      release_tag: v${{ steps.version_number.outputs.version }}
    env:
      KEYSTORE_FILE: ${{ github.workspace }}/../subsurface.keystore
      QT_ARCH: 'android_arm64_v8a'
      ANDROID_BUILD_ABI: 'arm64-v8a'
      BUILDROOT: '/android'
    runs-on: ubuntu-24.04
    # the container version is created in android-dockerimage.yml and is based
    # on the Qt version plus a running count of container builds for that version
    container:
      image: subsurface/android-build:6.10.3-2

    steps:
    - name: checkout sources
      uses: actions/checkout@v7
      with:
        fetch-depth: 0
        submodules: recursive

    - name: create links to sync standalone and GitHub filesystem
      run: |
        ln -s "$GITHUB_WORKSPACE" ${BUILDROOT}/src/subsurface

    - name: build Subsurface-mobile
      env:
        BUILD_TYPE: ${{ github.event_name == 'pull_request' && 'debug' || 'release' }}
      run: |
        mkdir -p build-android
        ln -s $(pwd)/build-android ${BUILDROOT}/build-android
        bash -x ${GITHUB_WORKSPACE}/packaging/android/in-container-build.sh
        find /android/build-android/android-build/ -name "*.apk"

    - name: collect APK
      run: |
        APK=$(find /android/build-android/android-build -name "*.apk" | head -1)
        cp "${APK}" "${GITHUB_WORKSPACE}/Subsurface-mobile.apk"

    - name: build AAB  # just to validate that that build isn't broken
      run: |
        cd /android/build-android/android-build
        ./gradlew bundleRelease

        AAB=$(find . -name "*.aab" | head -1)
        cp "${AAB}" "${GITHUB_WORKSPACE}/Subsurface-mobile.aab"

    - name: publish pull request artifacts
      uses: actions/upload-artifact@v7
      with:
        name: Subsurface-Android
        path: |
          Subsurface-mobile*.apk
