name: Android

on:
  push:
    paths-ignore:
    - scripts/docker/**
  pull_request:
    paths-ignore:
    - scripts/docker/**

jobs:
  build:
    env:
      KEYSTORE_FILE: ${{ github.workspace }}/../subsurface.keystore
    runs-on: ubuntu-latest
    container:
      image: docker://subsurface/android-build:5.15.2

    steps:
    - name: checkout sources
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: run build
      id: build
      run: |
        # this is rather awkward, but it allows us to use the preinstalled
        # Android and Qt versions with relative paths
        cd ..
        ln -s /android/5.15.* .
        ln -s /android/build-tools .
        ln -s /android/cmdline-tools .
        ln -s /android/ndk .
        ln -s /android/platform-tools .
        ln -s /android/platforms .
        ln -s /android/tools .
        git config --global user.email "ci@subsurface-divelog.org"
        git config --global user.name "Subsurface CI"
        git config --global --add safe.directory $GITHUB_WORKSPACE
        git config --global --add safe.directory $GITHUB_WORKSPACE/libdivecomputer
        # get the build number via curl so this works both for a pull request as well as a push
        export OUTPUT_DIR="$GITHUB_WORKSPACE"
        bash -x ./subsurface/packaging/android/qmake-build.sh

    - name: publish pull request artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Subsurface-Android
        path: Subsurface-mobile-*.apk
