name: Windows

on:
  push:
    paths-ignore:
    - scripts/docker/**
  pull_request:
    paths-ignore:
    - scripts/docker/**

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://subsurface/mxe-build:3.3.0

    steps:
    - name: checkout sources
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: get other dependencies
      env:
         SUBSURFACE_REPO_PATH: ${{ github.workspace }}
      run: |
        echo "Running script to install additional dependancies into container"
        git config --global --add safe.directory ${SUBSURFACE_REPO_PATH}
        git config --global --add safe.directory ${SUBSURFACE_REPO_PATH}/libdivecomputer
        cd /win
        ln -s /__w/subsurface/subsurface .
        bash -x subsurface/packaging/windows/container-prep.sh 2>&1 | tee pre-build.log

    - name: run build
      run: |
        export OUTPUT_DIR="$GITHUB_WORKSPACE"
        cd /win
        bash -x subsurface/packaging/windows/in-container-build.sh 2>&1 | tee build.log
        grep "Built target installer" build.log

    - name: publish pull request artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Subsurface-Windows
        path: |
         subsurface*.exe*
         smtk2ssrf*.exe

