name: Windows

on:
  push:
    paths-ignore:
    - scripts/docker/**
  pull_request:
    paths-ignore:
    - scripts/docker/**

env:
  RELEASE_PUBLISHER: "true"

permissions: read-all

jobs:
  build-documentation:
    uses: ./.github/workflows/documentation-build.yml
    with:
      container-image: docker://subsurface/mxe-build:3.4.0

  build:
    needs: build-documentation
    outputs:
      release_tag: v${{ steps.version_number.outputs.version }}
    runs-on: ubuntu-24.04
    container:
      image: docker://subsurface/mxe-build:3.4.0

    steps:
    - name: install packages
      run: |
        apt-get -y update

    - name: checkout sources
      uses: actions/checkout@v7
      with:
        fetch-depth: 0
        submodules: recursive

    - name: load the documentation from cache
      id: load-cache
      uses: actions/cache@v6
      with:
        path: Documentation/output
        key: documentation-${{ hashFiles('.github/workflows/documentation-build.yml', 'Documentation') }}
        enableCrossOsArchive: true
        fail-on-cache-miss: true

    - name: get other dependencies
      env:
         SUBSURFACE_REPO_PATH: ${{ github.workspace }}
      run: |
        echo "Running script to install additional dependancies into container"
        git config --global --add safe.directory ${SUBSURFACE_REPO_PATH}
        git config --global --add safe.directory ${SUBSURFACE_REPO_PATH}/libdivecomputer
        cd /win
        ln -s /__w/subsurface/subsurface .
        bash -x subsurface/packaging/windows/container-prep.sh 2>&1 | tee pre-build.log

    - name: run build
      run: |
        BUILD_EXTRA_ARGS=""
        if [ "${GITHUB_EVENT_NAME}" = "push" ]; then
          echo "Building a release version"
          BUILD_EXTRA_ARGS="${BUILD_EXTRA_ARGS} -release"
        fi

        export OUTPUT_DIR="$GITHUB_WORKSPACE"
        cd /win
        bash -x subsurface/packaging/windows/in-container-build.sh ${BUILD_EXTRA_ARGS} -install-docs 2>&1 | tee build.log
        grep "Built target installer" build.log

    - name: publish pull request artifacts
      uses: actions/upload-artifact@v7
      with:
        name: Subsurface-Windows
        path: |
         subsurface*.exe*
         smtk2ssrf*.exe

